### PR TITLE
Fix output of gatingset_to_cytobank to produce valid XML

### PR DESCRIPTION
**Pull request by whitews**
Relates to #69 

This PR fixes the XML output from the `gatingset_to_cytobank` function to produce valid XML. The changes required were all related to missing attribute namespaces.

The only issue remaining is to use a new "CytobankML" XSD instead of the GatingML 2.0 XSD, since the Cytobank format is not 100% valid GatingML. I have created this new XSD locally, but it needs to be hosted somewhere. After that the XSD reference in the output XML should be changed, and I've left a `TODO` comment in the code concerning this.

I ran the testthat script before and after the commits in this PR. Before this PR there were 9 tests that failed. These same tests fail after these commits, with no new failures.

### CODE REVIEW

**Comment by mikejiang** [comment]
XSD reference was hardcoded by `flowUtils::write.gatingML`, which you can either request its author () for adding the optional argument that allows for customization or simply adding the post-processing step to the output XML.  I am open for another PR as well as host new xsd file in this repo.

**Comment by whitews** [comment]
Yes, I can submit another PR that has the modification to the new XSD reference. The issue is that it needs to be hosted somewhere. The best place would probably be on the cytobank site itself, since it is their convention after all. Do you guys have any connections with the Cytobank team?

**Comment by mikejiang** [comment]
The point of contact left the company even before it is sold to Beckman Coulter.

**Comment by whitews** [comment]
Okay, do you mind if I reach out to Cytobank to inquire about hosting the XSD?

**Comment by gfinak** [comment]
I'd suggest just hosting it as part of the cytoml repo.

**Comment by whitews** [comment]
@gfinak Personally, I'm happy with that, but if this is an official format dictated by Cytobank, then they are the most appropriate entity to host it. Do they use the RGLab suite of R libraries on the back end to create these files?

**Comment by mikejiang** [comment]
At some point, they were trying to use our tool to port flowjo xml to cytobank, but I don't know if the feature was ever completed or rolled into their release.

**Comment by whitews** [comment]
Okay then, if they aren't willing to be transparent, I agree that CytoML should host the XSD. I'll work on another PR to add the XSD and the modifications necessary to reference it in the output XML file. Perhaps we should start referencing this format as the "CytoML" standard? Regardless, I'll then add support for it in my FlowKit library, so users will have the option of using R or Python for flow analysis.

**Pull request merged**
